CREATE TABLE [dbo].[ALB_CLIENTE] (
    [NR_ID_CLIENTE] INT        NOT NULL,
    [VC_NOME]       NCHAR (10) NULL,
    [VC_SOBRENOME]  NCHAR (10) NULL,
    [VC_EMAIL]      NCHAR (100) NULL,
    [VC_TELEFONE]   NCHAR (10) NULL,
    PRIMARY KEY CLUSTERED ([NR_ID_CLIENTE] ASC)
);

